version: "3.8"
services:
  app:
    build: .
    image: johnkristan01/teachflow:latest
    env_file:
      - .env

    container_name: teachflow_AI
    ports:
      - "8000:8000"
    environment: 
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres.opmshbvejnunxhahncig:teachflow-root-db@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
    depends_on:
      - rabbitmq


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest


