"""Alter essay_id to integer type

Revision ID: 754628eb9012
Revises: a47489ac3ad5
Create Date: 2025-06-14 10:34:23.716329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '754628eb9012'
down_revision: Union[str, None] = 'a47489ac3ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    # 2. Clear data from the column (accepting data loss)
    op.execute("UPDATE essay_evaluations SET essay_id = NULL WHERE essay_id IS NOT NULL;")

    # 3. Alter the column type to Integer
    op.alter_column('essay_evaluations', 'essay_id',
                    existing_type=sa.String(), # Or postgresql.UUID if that was the original
                    type_=sa.Integer(),
                    existing_nullable=True, # Based on your current model, but might be False if previously not null
                    nullable=False, # Set to False if it should be NOT NULL now
                    postgresql_using='NULL' # No actual casting, setting to NULL first
    )

    # 2. Clear data from the column (accepting data loss)
    op.execute("UPDATE essay_summaries SET essay_id = NULL WHERE essay_id IS NOT NULL;")

    # 3. Alter the column type to Integer
    op.alter_column('essay_summaries', 'essay_id',
                    existing_type=sa.String(), # Or postgresql.UUID
                    type_=sa.Integer(),
                    existing_nullable=True, # Or existing_nullable=False if it was already NOT NULL
                    nullable=False, # Set to False if it should be NOT NULL now
                    postgresql_using='NULL' # No actual casting, setting to NULL first
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrading involves converting Integer back to UUID/String.
    # This WILL LOSE DATA in these columns, as there's no reverse mapping.
    # It's often best to treat such migrations as one-way in development.

    # --- Downgrade essay_summaries ---
    op.alter_column('essay_summaries', 'essay_id',
                    existing_type=sa.Integer(),
                    type_=sa.String(), # Or postgresql.UUID
                    nullable=True,
                    existing_nullable=False) # Data will be lost here

    op.alter_column('essay_evaluations', 'essay_id',
                    existing_type=sa.Integer(),
                    type_=sa.String(), # Or postgresql.UUID
                    nullable=True,
                    existing_nullable=False) # Data will be lost here
    # ### end Alembic commands ###